name       : closure-compiler
version    : '20210202'
release    : 3
source     :
    - https://github.com/google/closure-compiler/archive/v20210202.tar.gz : de4a41fa6cfd524548f508a4b078677a6cac351dc665233473c1dc5bef102800
license    : Apache-2.0
homepage   : https://developers.google.com/closure/compiler/
component  : programming.java
summary    : A JavaScript checker and optimizer
description: |
    The Closure Compiler is a tool for making JavaScript download and run faster. It is a true compiler for JavaScript. Instead of compiling from a source language to machine code, it compiles from JavaScript to better JavaScript. It parses your JavaScript, analyzes it, removes dead code and rewrites and minimizes what's left. It also checks syntax, variable references, and types, and warns about common JavaScript pitfalls.
networking : yes
builddeps  :
    - bazel
    - git
    - python-docutils
rundeps    :
    - openjdk-11
setup      : |
    rm .bazelrc
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    bazel build //:compiler_shaded --define=COMPILER_VERSION=%version%.0.0
install    : |
    install -Dm00644 bazel-bin/compiler_shaded.jar $installdir/usr/share/java/closure-compiler/closure-compiler.jar
    install -Dm00755 $pkgfiles/closure-compiler $installdir/usr/bin/closure-compiler
    rst2man debian/closure-compiler.1.txt > debian/closure-compiler.1.tmp
    cat debian/manpage_encoding_declaration.UTF-8 debian/closure-compiler.1.tmp > debian/closure-compiler.1
    install -Dm00644 debian/closure-compiler.1 $installdir/usr/share/man/man1/closure-compiler.1
