name       : closure-compiler
version    : '20200517'
release    : 2
source     :
    - https://github.com/google/closure-compiler/archive/v20200517.tar.gz : 6be4e078fc707eff4a39bdbce9e9462973bb9a32d2b65426f2d77c5e9c68aa76
license    : Apache-2.0
homepage   : https://developers.google.com/closure/compiler/
component  : programming.java
summary    : A JavaScript checker and optimizer
description: |
    The Closure Compiler is a tool for making JavaScript download and run faster. It is a true compiler for JavaScript. Instead of compiling from a source language to machine code, it compiles from JavaScript to better JavaScript. It parses your JavaScript, analyzes it, removes dead code and rewrites and minimizes what's left. It also checks syntax, variable references, and types, and warns about common JavaScript pitfalls.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    mvn -Dmaven.repo.local=../local-repo -DskipTests -T%YJOBS% \
        -pl externs/pom.xml,pom-main.xml,pom-main-shaded.xml,pom-linter.xml \
install    : |
    pushd closure-compiler-%version%
    install -Dm00644 target/closure-compiler-1.0-SNAPSHOT.jar \
        $installdir/usr/share/java/closure-compiler/closure-compiler.jar
    install -Dm00644 target/closure-compiler-linter-1.0-SNAPSHOT.jar \
        $installdir/usr/share/java/closure-compiler/closure-compiler-linter.jar
    install -Dm00755 $pkgfiles/closure-compiler $installdir/usr/bin/closure-compiler
    install -Dm00755 $pkgfiles/closure-compiler-linter $installdir/usr/bin/closure-compiler-linter
